export default (tcHandle) => 
[{k: "tc1", html: `1: HABITACIONAL, PRECARIA (HAB)`, handleClickItem: tcHandle, i: 1},{k: "tc2", html: `2: HABITACIONAL, ECONOMICA (HBB)`, handleClickItem: tcHandle, i: 2},
 {k: "tc3", html: `2.5: HABITACIONAL, INTERES SOCIAL (HCB)`, handleClickItem: tcHandle, i:2.5},{k: "tc4", html: `3: HABITACIONAL, REGULAR (HDB)`, handleClickItem: tcHandle, i:3},
 {k: "tc5", html: `4: HABITACIONAL, INTERES MEDIO (HEB)`, handleClickItem: tcHandle, i:4},{k: "tc6", html: `5: HABITACIONAL, BUENA (HFB)`, handleClickItem: tcHandle, i:5},
 {k: "tc7", html: `6.5: HABITACIONAL, MUY BUENA (HGB)`, handleClickItem: tcHandle, i:6.5},{k: "tc8", html: `37.5: COMERCIAL, ECONOMICA (CAB)`, handleClickItem: tcHandle, i:37.5},
 {k: "tc9", html: `40: COMERCIAL, REGULAR (CBB)`, handleClickItem: tcHandle, i:40},{k: "tc10", html: `43.5: COMERCIAL, BUENA (CCB)`, handleClickItem: tcHandle, i:43.5},
 {k: "tc11", html: `44: COMERCIAL, MUY BUENA (CDB)`, handleClickItem: tcHandle, i:44},{k: "tc12", html: `51: COMERCIAL, CENTRO COMERCIAL (CEB)`, handleClickItem: tcHandle, i:51},
 {k: "tc13", html: `54.5: COMERCIAL, TIENDA DE AUTOSERVICIO (CFB)`, handleClickItem: tcHandle, i:54.5},{k: "tc14", html: `63: COMERCIAL, TIENDA DEPARTAMENTAL (CGB)`, handleClickItem: tcHandle, i:63},
 {k: "tc15", html: `8: INDUSTRIAL, ECONOMICA (IAB)`, handleClickItem: tcHandle, i:8},{k: "tc16", html: `9.5: INDUSTRIAL, LIGERA (IBB)`, handleClickItem: tcHandle, i:9.5},
 {k: "tc17", html: `14: INDUSTRIAL, MEDIANA (ICB)`, handleClickItem: tcHandle, i:14},{k: "tc18", html: `2: EDIFICIOS DE OFICINA, REGULAR (OAB)`, handleClickItem: tcHandle, i:2},
 {k: "tc19", html: `2: EDIFICIOS DE OFICINA, BUENA (OBB)`, handleClickItem: tcHandle, i:2},{k: "tc20", html: `3: EDIFICIOS DE OFICINA, MUY BUENA (OCB)`, handleClickItem: tcHandle, i:3},
 {k: "tc21", html: `12: INSTALACIONES ESPECIALES, CISTERNAS (EAB)`, handleClickItem: tcHandle, i:12},{k: "tc22", html: `47: INSTALACIONES ESPECIALES, ELEVADORES (EBB)`, handleClickItem: tcHandle, i:47},
 {k: "tc23", html: `2: O. COMPLEMENTARIAS, ESTACIONAMIENTO DESCUBIERTO (FAB)`, handleClickItem: tcHandle, i:2},{k: "tc24", html: `5: O. COMPLEMENTARIAS, ESTACIONAMIENTO CUBIERTO (FBB)`, handleClickItem: tcHandle, i:5},
 {k: "tc25", html: `4: O. COMPLEMENTARIAS, ALBERCA (FCB)`, handleClickItem: tcHandle, i:4},{k: "tc26", html: `1: O. COMPLEMENTARIAS, CANCHA DE FUTBOL (FDB)`, handleClickItem: tcHandle, i:1},
 {k: "tc27", html: `1: O. COMPLEMENTARIAS, CANCHA DE BASQUETBOL (FEB)`, handleClickItem: tcHandle, i:1},{k: "tc28", html: `2: O. COMPLEMENTARIAS, BARDAS DE TABIQUE (FIB)`, handleClickItem: tcHandle, i:2},
 {k: "tc29", html: `2: O. COMPLEMENTARIAS, AREAS JARDINADAS (FJB)`, handleClickItem: tcHandle, i:2},{k: "tc30", html: `2: O. COMPLEMENTARIAS, VIALIDADES, ANDADORES Y BANQUETAS (FLB)`, handleClickItem: tcHandle, i:2}]
